# Generated by Django 3.1.2 on 2020-12-23 09:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('M', 'mensuel'), ('A', 'annuel')], default='A', max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bill', models.FileField(upload_to='purchase/bills')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRD.item')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('due_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('bill', models.FileField(upload_to='purchase/bills')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRD.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SRD.itemtype'),
        ),
    ]
