# Generated by Django 3.1.2 on 2020-10-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_devtool_acronym'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='devtool',
            name='info_source',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devtool',
            name='tool_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.tooltype'),
        ),
    ]
