# Generated by Django 3.1.2 on 2020-10-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_devtool_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtool',
            name='acronym',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='devtool',
            name='info_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devtool',
            name='source_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
