# Generated by Django 3.1.2 on 2020-10-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20201016_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooltype',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
