# Generated by Django 3.1.2 on 2020-11-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20201019_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DevTool',
        ),
        migrations.DeleteModel(
            name='ToolFamily',
        ),
        migrations.DeleteModel(
            name='ToolType',
        ),
    ]
