# Generated by Django 3.1.2 on 2020-11-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0009_auto_20201119_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(upload_to='tools/')),
            ],
            options={
                'verbose_name_plural': 'Outils',
                'ordering': ['name'],
            },
        ),
    ]
