# Generated by Django 3.1.2 on 2020-11-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='logo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
