# Generated by Django 3.1.2 on 2020-11-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20201120_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('infos', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Etapes',
                'ordering': ['order'],
            },
        ),
    ]
