# Generated by Django 3.1.2 on 2020-11-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='primary',
            field=models.BooleanField(default=True),
        ),
    ]
