# Generated by Django 3.1.2 on 2020-11-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_steps_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps',
            name='details',
        ),
        migrations.RemoveField(
            model_name='steps',
            name='primary',
        ),
    ]
