# Generated by Django 3.1.2 on 2020-11-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20201121_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='infos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
