# Generated by Django 3.1.2 on 2020-11-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20201121_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tools',
            old_name='details',
            new_name='acronym',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='logo',
        ),
        migrations.AddField(
            model_name='tools',
            name='infos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
