# Generated by Django 3.1.2 on 2020-11-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20201122_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
