# Generated by Django 3.1.2 on 2020-11-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_tools_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tools',
            old_name='acronym',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='infos',
        ),
        migrations.AlterField(
            model_name='tools',
            name='logo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
