# Generated by Django 3.1.2 on 2020-11-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20201122_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='acronym',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
