# Generated by Django 3.1.2 on 2020-11-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20201122_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('logo', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
