# Generated by Django 3.1.2 on 2020-11-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='link',
            field=models.CharField(default='ok', max_length=200),
            preserve_default=False,
        ),
    ]
