# Generated by Django 3.1.2 on 2020-11-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_contact_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
