# Generated by Django 3.1.2 on 2020-11-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_project_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-order']},
        ),
        migrations.AddField(
            model_name='project',
            name='img2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
