# Generated by Django 3.1.2 on 2020-11-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_auto_20201124_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.project')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.tools')),
            ],
        ),
    ]
