# Generated by Django 3.1.2 on 2020-11-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_toolsassociation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToolsAssociation',
        ),
    ]
